### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by tabbi89** [SolarNetwork/killbill-invoice-formatter#1]
Hi,

A bit unclear how to deploy plugin for a rookie. "The JAR must be included on the Kill Bill class path. This can be accomplished by adding it to the WEB-INF/lib directory of the WAR." I have no idea where such a lib exists., especially in kill bill docker.

Best regards

**Comment by msqr** [comment]
Hi @tabbi89,

I'm not familiar with the Docker based deployments as I don't use that approach. For me, I take the Killbill WAR file, like `killbill-profiles-killbill-0.8.20.war`, and add `sn-killbill-invoice-formatter-0.1.1.jar` into the `WEB-INF/lib` directory of the WAR, e.g.

```bash
mkdir WEB-INF/lib
mv sn-killbill-invoice-formatter-0.1.1.jar WEB-INF/lib
jar uvf killbill-profiles-killbill-0.8.20.war WEB-INF/lib/*.jar
```

You could ask on the KB mailing list for help with adding a plugin JAR to the Docker image.

**Comment by msqr** [comment]
Hi @tabbi89,

Were you able to incorporate this formatter into your Docker image?

**Comment by msqr** [comment]
Closing from lack of feedback.
